spring.application.name=cloudsql
spring.datasource.url=jdbc:postgresql://localhost:5432/cloudsql2
spring.datasource.username=postgres
spring.datasource.password=Pawel123
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8080}

logging.level.org.springframework.security=DEBUG
logging.level.org.flywaydb=DEBUG
spring.graphql.graphiql.enabled=true